version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    image: php:8.0-apache
    volumes:
      - ./public:/var/www/html/
    environment:
      - FLAG=havceCTF{never_trust_PHP_WplAhwAxDnr}
    ports:
      - 8000:80